name: Release

on:
  push:
    tags:
      - v*

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run export
      - name: Create archive
        run: tar -czvf release.tar.gz out 
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: release.tar.gz
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: 
      - export
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: release
    - run: mv release.tar.gz tdp-ui-${{ github.ref_name }}.tar.gz
    - name: Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        name: Release ${{ github.ref_name }}
        generate_release_notes: true
        files: tdp-ui-${{ github.ref_name }}.tar.gz
        draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
